# Generated by Django 3.1.3 on 2021-09-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210929_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlobject',
            name='shorten_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
